### ISSUE TITLE
How to get regionInfo for a subscription?

### ISSUE THREAD

**Issue by jobinar** [Azure/BillingCodeSamples#14]
The [rate card API](https://msdn.microsoft.com/en-us/library/azure/mt219004.aspx):

`https://management.azure.com/subscriptions/{subscription-Id}/providers/Microsoft.Commerce/RateCard?api-version={api-version}&$filter=OfferDurableId eq ’{OfferDurableId}’ and Currency lt ’{Currency}’ and Locale eq ’{Locale}’ and RegionInfo eq ’{RegionInfo}’’`

requires the `regionInfo` to be provided for each request. The `regionInfo`, according to the documentation, refers to the location where the offer was purchased (offer referring to the `OfferDurableId`). The OfferDurableId can be obtained from the subscription and subsequently from [here](http://azure.microsoft.com/en-us/support/legal/offer-details/). However, I didn't find the regionInfo anywhere.

How to get the `regionInfo` for a subscription?

**Comment by moinak3** [comment]
You can go to https://account.windowsazure.com/Profile and then view the address on file to figure out the account region. Once a sub is started, the country cannot be changed.

**Comment by rnithish** [comment]
Can this RegionInfo be accessed through code/API ?
